Portfolio Finish Mobile version
Isaac-ej/Portfolio_Website pull request #9
Opened 2023-06-06 21:37 UTC by Isaac-ej

This is the Personal Portfolio Finish Mobile version feature which includes 

- works section built utilizing CSS Grid to place elements on the works section.
- about section Flexbox was used to place elements in the About section.

2023-06-06 21:57 UTC, stanleySimeon requested changes
# Hi @Isaac-ej, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that doesn't have the changes requested by the previous reviewer, kindly I suggest you not merge the PR while it does not approve yet.
Please, make sure you submit a good PR.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-06-06 22:33 UTC, shahadat3669 requested changes
Hi @Isaac-ej , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

<img src="https://media1.giphy.com/media/jmqAUNFXAElgafPK0g/giphy.gif"/>

## Invalid Code Review Request

You have submitted a project that is not valid. I would like to suggest that you resubmit your previous pull request (PR) that contains the changes requested by the reviewer for this milestone. Typically, for each milestone, it is expected to have only one PR unless the reviewer explicitly asks for additional changes. Therefore, it would be best to submit your previous PR with the required changes.

By resubmitting the previous PR, you ensure that the changes requested by the reviewer are properly addressed and considered. This will help maintain a clear and organized workflow for the project. Thank you for your understanding, and please let me know if you have any questions or need further assistance.


Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-06-07 07:34 UTC, ahmetbozaci commented
### Hello @Isaac-ej 
### _This is an additional review as a result of the second opinion request._ 

- In all reviews' end of the summaries, this text includes `Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.` This makes the review process easy. Please don't open new pull requests or new repos for your future project. 
- [ ] Please submit your pull request next review will review it.

- [ ] Next code reviewer please re-review this pull request according to the [this pull request.](https://github.com/Isaac-ej/Portfolio_Website/pull/8)

___

**Attention to reviewers** 
@shahadat3669 and @stanleySimeon: If you can't see the previous review, please don't make it invalid. It is not an invalidation reason. You have two options in such cases:
1- Search for the first review in the closed pull request, which can be found [here](https://github.com/Isaac-ej/Portfolio_Website/pull/8). If you locate the previous review, you can do a re-review.
2- If you are unable to find the first review, please you are free to review it as a first review.
Thank you for your attention and dedication to conducting thorough reviews.

### Cheers and Happy coding! 💻 👏
____
[GitHub](https://github.com/ahmetbozaci) | [LinkedIn](https://linkedin.com/in/ahmetbozaci) | [Twitter](https://twitter.com/ahmtbozaci)

_Reviewed by [Ahmet Bozacı ](https://github.com/ahmetbozaci)_

2023-06-07 07:43 UTC, Lameck1 reviewed
Hello, @Isaac-ej👋,

_This is an additional review as a result of the second opinion request._

The invalidation from the previous reviewer is in line with our code review policy. You created a new PR without explaining why and the Code Reviewers figure out whether your reasoning is valid or not.

The Second Opinion process is not for solving invalidations on the PR but for disputes that might arise on a given code review.

You should take it as a challenge and resolve the issues you had in the earlier PR. The issues you are experiencing are part of the learning process. When you get to be a part of an engineering team, deleting/abandoning PRs and creating new ones due to merge conflicts will not be an OPTION. You MUST learn how to resolve them and continue the development process.

With all that said, we'll allow code review to continue on this newly created PR. But, you MUST vividly explain to the CRs what happening. Don't forget to provide a link to the previous PR so that the CRs can justify your claims.

As you advance your learning at Mcroverse, this exception will not be there.

Keep rocking 🚀!

2023-06-07 09:06 UTC, NahnahAJ requested changes
## Project Status: CHANGES REQUIRED :recycle: 
Hi @Isaac-ej , 

After referencing this PR #8, Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which haven't been addressed yet.
<img src="https://media2.giphy.com/media/m3864rBwwBTKMAbpn3/giphy.gif"/>

 ## Highlights :fire: 
-  Linters well setup and passing :heavy_check_mark: 
- Good use of GitHub flow :heavy_check_mark: 
- Professional README :heavy_check_mark: 

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @NahnahAJ in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-07 09:06 UTC, nahnahdev commented on index.html
> +  </section>
- [ ] Great job putting the works in a (`section` tag) as the previous reviewers suggested. However, I noticed that currently, you have only one work card or project card in your project. Instead of the original 4 cards as seen in the Figma design. :+1: 
- I also noticed that you didn't use `display:grid` to style the `work section` as the previous reviewers mentioned so kindly add the other 3 cards in the works section and ensure that the section is properly styled with `display:grid` :wink: 
- Your Design 

[Screencast from 06-07-2023 08:32:24 AM.webm](https://github.com/Isaac-ej/Portfolio_Website/assets/102699958/020714a8-c211-49c1-9e93-d57766e5bb21)

- The Figma Design

[Screencast from 06-07-2023 08:31:39 AM.webm](https://github.com/Isaac-ej/Portfolio_Website/assets/102699958/7c080912-c8cd-435d-b9b7-bf16d86a2cf8)

2023-06-07 09:06 UTC, nahnahdev commented on style.css
> +}
- [ ] I noticed that you implemented the button interaction styles for the button when on hover. However, your styles are not similar to that of the Figma design. Your background color when on hover is currently different from what you had previously and what is seen in the Figma design. So kindly refer to the Figma design and fix that as well :+1: 
- Aside from this, I noticed you didn't implement the button-pressed or `:active `styles as the previous reviewers mentioned. So kindly include that as well :wink: 

| Your Button on Hover and Pressed | The Figma Design |
|--------|--------|
| ![image](https://github.com/Isaac-ej/Portfolio_Website/assets/102699958/5fa84f87-2b2e-4af0-adf6-7a4fe4e50a1e) | ![image](https://github.com/Isaac-ej/Portfolio_Website/assets/102699958/4790b079-6575-4b70-badb-9c8bc0e534c3) |

2023-06-07 09:06 UTC, nahnahdev commented on index.html
> +        <h1 class="about-h1-b">About Myself</h1>
- [ ] Just as the previous reviewers mentioned, kindly make sure to only use one `h1` element per page in accordance with the proper HTML semantics. Since you made use of the `h1` tag previously in your `headline section`, I will suggest that you change this to one of the other (`hx` tags). Eg. (`h2`,`h3`,`h4` etc) :100:

2023-06-07 09:06 UTC, NahnahAJ commented on index.html
> +
- [ ] Lastly, I noticed that after implementing the changes requested, some parts of your design have changed and don't look quite similar to the Figma design :+1: 
- From the images below, you can see that in your design, at the end of the works section, and on top of the About section, there is a square rectangular shape that is currently disrupting the design and not making it look like the Figma design. So kindly remove this from your design so your design looks exactly like the Figma design :wink: 

| Your Design | The Figma Design |
|--------|--------|
| ![image](https://github.com/Isaac-ej/Portfolio_Website/assets/102699958/bd5b60aa-d00e-4974-95b6-5fb94086ee46) | ![image](https://github.com/Isaac-ej/Portfolio_Website/assets/102699958/fffac147-7136-4edc-ab3d-f5a296368187) |

2023-06-07 11:37 UTC, aamirkhan2478 requested changes
Hi @Isaac-ej , 

![](https://media3.giphy.com/media/RcZlXVml8oKtoGQeqe/giphy.gif?cid=ecf05e47cw5pjd1gapdzk1t3vp0n73caujoqxw3vkcu8ssng&rid=giphy.gif&ct=g)

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't been addressed yet.

 ## Highlights
✔️ Good Effort
✔️ Your design is good.
✔️ All linters passed

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-07 11:37 UTC, aamirkhan2478 commented on index.html
> +        <button type="submit" class="btn-a ">See Projects</button>
- [ ] Well done :clap: you did almost all changes given by the previous reviewer :point_up_2: but I noticed that you did fix your button style and hover, active etc effects so kindly fix this issue :+1: check below :point_down: the comparison between your design and Figma's design :slightly_smiling_face:

| Your Design | Figma Design|
|--------|--------|
| ![Screenshot from 2023-06-07 16-27-52](https://github.com/Isaac-ej/Portfolio_Website/assets/45226848/c553c911-2de8-41e2-94b6-ee78e7b90eae) | ![Screenshot from 2023-06-07 16-30-29](https://github.com/Isaac-ej/Portfolio_Website/assets/45226848/ce203af2-319e-43c3-92d6-7a24182c7624) |  

_**The following :point_down: are the button effects so kindly apply these all effects given below**_

![Screenshot from 2023-02-17 17-31-04](https://github.com/Isaac-ej/Portfolio_Website/assets/45226848/d0be23b3-fd48-4002-8b81-5aa587fa1238)

2023-06-07 13:22 UTC, Efiamotu-1 approved these changes
Hi @Isaac-ej , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

# STATUS: APPROVED 🕺🥳 

![giphy](https://user-images.githubusercontent.com/89055502/234114221-4ca295de-fd8f-4af6-9c49-a6d4c6ea67f7.gif)


## Highlights :dart: 
* Correct GitHub flow :heavy_check_mark: 
* Good commit messages :heavy_check_mark: 
* All linters passing :heavy_check_mark: 
* Good PR summary :heavy_check_mark: 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

## Important Notes 📝

- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
- Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

> **Note:** Please, you can now Merge since it is Approved ✅, However if there are any conflicts please resolve them before merging.


## Thank you for your time 🙏 and call me if you need help or clarification ☎️

- This is My **GitHub**: [![@Efiamotu-1](https://img.shields.io/github/followers/Efiamotu-1?label=Habeeb-Efiamotu-Musa&style=social)](https://github.com/Efiamotu-1/)
- This is My **linkedIn**.[![Habeeb Efiamotu Musa](https://img.shields.io/badge/linkedin-@Habeeb-crimson)](https://www.linkedin.com/in/musa-habeeb/)
- This is My **Twitter**: [![@EFYAMOTU](https://img.shields.io/twitter/follow/omarramoun?label=Habeeb-Efiamotu-Musa&style=social)](https://twitter.com/EFYAMOTU)
- This is My **Slack**: [![Habeeb Efiamotu Musa ](https://img.shields.io/badge/slack-@Habeeb-brightgreen)](https://slack.com)

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-07 16:43 UTC, merged